@startuml Generate short functions flow
title Generate Ad functions flow

generateAd -> fetchChatGptAnswer : product link
fetchChatGptAnswer -> generateAd : narration text

generateAd -> fetchAudioUrl : narration text
fetchAudioUrl -> generateAd : narration audio

generateAd -> generateVideo : image and narration audio
generateVideo -> generateAd : video download link
@enduml