@startuml Project Architecture

Title Project Architecture

actor User
box front-end
    participant WebPage

    User -> WebPage : inputs link and image

    WebPage -> ChatGPT_API: requests copyright text
    ChatGPT_API -> WebPage: response with copyright text
end box

box back-end
    WebPage -> CreateVideo_API: requests custom video, seding text and image
    
    CreateVideo_API -> CreateNarration_API: requests custom audio, seding text
    CreateNarration_API -> CreateVideo_API: response with custom audio

    CreateVideo_API -> CreateVideo_FUNCTION: calls function to create video, seding audio and image
    CreateVideo_FUNCTION -> CreateVideo_API: returns video

    CreateVideo_API -> WebPage: response with link to download video
end box

    WebPage -> User : displays button to download video


@enduml