@startuml Project Architecture

Title Project Architecture

actor User
box front-end
    participant WebPage

    User -> WebPage : inputs link, image and language
    WebPage -> CreateVideo_FUNCTION: requests custom video, seding link and image

end box

box back-end
    
    CreateVideo_FUNCTION -> ChatGPT_API: requests copyright text
    ChatGPT_API -> CreateVideo_FUNCTION: response with copyright tex
    
    CreateVideo_FUNCTION -> CreateNarration_API: requests custom audio, seding text
    CreateNarration_API -> CreateVideo_FUNCTION: response with custom audio

    CreateVideo_FUNCTION -> CreateVideo_FUNCTION: calls function to create video, seding audio and image
    CreateVideo_FUNCTION -> CreateVideo_FUNCTION: returns video

    CreateVideo_FUNCTION -> WebPage: response with link to download video
end box

    WebPage -> User : displays button to download video


@enduml